"""Update borrowedbook

Revision ID: 57be8b0402ab
Revises: 23acad06cce2
Create Date: 2025-05-22 12:29:10.057916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57be8b0402ab'
down_revision: Union[str, None] = '23acad06cce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_book_reader_return', 'borrowedbooks', ['book_id', 'reader_id', 'return_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_book_reader_return', 'borrowedbooks', type_='unique')
    # ### end Alembic commands ###
