"""Update borrowedbook

Revision ID: efbc7ba8fddf
Revises: 57be8b0402ab
Create Date: 2025-05-22 12:37:54.889222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbc7ba8fddf'
down_revision: Union[str, None] = '57be8b0402ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_book_reader_return', 'borrowedbooks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_book_reader_return', 'borrowedbooks', ['book_id', 'reader_id', 'return_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
