"""Update borrowedbook

Revision ID: f3933f42f5f8
Revises: efbc7ba8fddf
Create Date: 2025-05-22 13:23:16.604142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3933f42f5f8'
down_revision: Union[str, None] = 'efbc7ba8fddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_book_reader_active', 'borrowedbooks', ['book_id', 'reader_id'], unique=True, postgresql_where=sa.text('return_date IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_book_reader_active', table_name='borrowedbooks', postgresql_where=sa.text('return_date IS NULL'))
    # ### end Alembic commands ###
